/**
 * 🔒 ЗЛІПОК ДОСТУПУ — знято ЕМПІРИЧНО з прода 31.07.2026 (450 пар роль×ендпоінт).
 *
 * Це НЕ побажання, а фотографія «як є» ПЕРЕД рефакторингом хардкоду ролей. Її
 * призначення — зловити будь-яку зміну поведінки під час заміни `role === "admin"`
 * на `roleHasPerm`. Рефакторинг не має права змінити жодну клітинку; змінив —
 * це вже не рефакторинг, а зміна політики, і робиться вона окремо й свідомо.
 *
 * 🔵 ПОВНЕ ПОКРИТТЯ 01.08.2026 (крок B1). Було 65 роутів зі 177 — «зелена там, куди
 * ми подивились», і саме в непокритій частині сидів інцидент з HR. Тепер у зліпку ВСІ
 * 177 роутів: 92 GET · 17 DELETE-ghost · 68 deny-only.
 *
 * Шляхи беруться з РАНТАЙМ-обходу роутерів (`routeInventory.ts`), а не з регулярки:
 * статичний розбір уже підводив (kvp-report виглядав відкритим, а віддає 403).
 *
 * ⚠️ ЗНЯТО З ПРОДА, НЕ З ПІСОЧНИЦІ. Спроба взяти deny-набори мутацій із пісочниці дала
 * 158 розбіжностей із 310 пар: без даних поведінка інша. Пісочниця не еталон.
 *
 * ⏱ Повний прогін ≈ втричі довший — тому поділ: `npm test` (швидкий, без #11) і
 * `npm run test:matrix` (повний). Обидва названі в маніфесті.
 *
 * 🟢 ОНОВЛЕНО 02.08.2026 — ЗМІНА ПОЛІТИКИ (такт 2): 17 роутів дістали tab-межу.
 * Зрушило РІВНО 8 клітинок, і всі в один бік — 200 → 403:
 *   hr:      kvp-report/manager-detail · report-plan · report-plan/deals ·
 *            response-time · stuck-deals-grouped · deal-note · lead-recommendation
 *   manager: lead-recommendation
 * Це НЕ звуження чиїхось прав, а закриття того самого класу, що дав інцидент з HR:
 * єдиною межею цих роутів був scope-кламп, а в company-ролі клампа немає. Жодна з
 * восьми ролей не втратила екран, який у неї Є: HR не має ні «report», ні «plans»,
 * ні «kvp»; менеджер не має «plans». Перевірено перед застосуванням по всіх 8 ролях.
 * Решта 9 мапінгів зрушили НУЛЬ клітинок — там ті самі ролі й так отримували 403.
 * Мапінги взяті з ФРОНТУ (який екран кличе роут), не з форми шляху.
 *
 * 🟢 ПЕРЕЗНЯТО 31.07.2026 — ЗМІНА ПОЛІТИКИ, НЕ РЕГРЕСІЯ.
 * Рішення власника: ФІНАНСИСТ ПРАЦЮЄ НА РІВНІ АДМІНА. Попередній дефолт «немає
 * вкладки → закрити ендпоінт» скасовано: 15 продажних ендпоінтів не закривали, а
 * роль вирівняли до адмінської (правами й екранами в `roles`, не хардкодом у роутах).
 *
 * Зрушило РІВНО 50 рядків, і в кожному зміна одна й та сама: `+financier`. Жодна
 * інша роль не додана, жодна не знята — перевірено перезніманням усіх пар тим самим
 * пробником проти сервера з новим кодом.
 *
 * ДВА ВИНЯТКИ лишились і перевірені окремо (обидва financier=403):
 *   • GET  /settings/users              — керування користувачами;
 *   • POST /settings/users/:id/reset-password — скидання паролів.
 *
 * ⚠️ У 14 рядках класу `deny-only` financier ЗНИК З ОБОХ списків, а не переїхав у
 * `allow`. Причина не косметична: ці рядки реально ЗАПИСУЮТЬ, і тест пробує лише
 * ролі зі списку `deny`. Лишити фінансиста там, де він тепер проходить гейт, означало
 * б, що наступний прогін #11 виконає справжній POST проти прода. Спіймав це #11b —
 * інваріант «у deny-only рядку не буває дозволених ролей» саме для цього й існує.
 *
 * ⚠️ ЯКЩО ЧИТАЄШ ЦЕ ЧЕРЕЗ ПІВРОКУ: широкі права фінансиста — НЕ баг і не наслідок
 * недогляду в рефакторингу. Це узгоджене рішення. Не «виправляй» назад.
 *
 * ⚠️ Чому емпірично, а не з розбору коду: статичний маппер «гейт → ендпоінт»
 * помилився на /dashboard/data-quality (приписав гейт не тому роуту). Зліпок із
 * живого API такої помилки не має за побудовою.
 *
 * КЛАСИ ПРОБИ — визначають, що тест має право робити на живому API:
 *  • GET          читання, пробуємо всі ролі;
 *  • DELETE-ghost DELETE з НЕІСНУЮЧОЮ ціллю: збігів немає, отже й запису немає;
 *  • deny-only    POST/PUT, що апсертять або запускають дію (напр. POST /dashboard/sync
 *                 стартує синк). Пробуємо ЛИШЕ ролі, яким гейт відмовляє; дозволені
 *                 не чіпаємо — вони б записали. Для них гарантія інша: гейт стоїть
 *                 ПЕРШИМ значущим оператором (перевірено читанням усіх обробників).
 *
 * Доведено знімком 70 таблиць до і після проби: жодного рядка, жодного штампа часу.
 *
 * `allow` = «сервер НЕ віддав 403». Код 400 (бракує параметрів) — теж пройдений гейт:
 * питання матриці — доступ, а не валідність запиту.
 */
export interface AccessRow {
  method: string;
  path: string;
  cls: "GET" | "DELETE-ghost" | "deny-only";
  /** Ролі, яким сервер віддав НЕ 403. */
  allow: string[];
  /** Ролі, яким сервер віддав 403. */
  deny: string[];
}

export const ACCESS_ROLES = ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"] as const;

export const ACCESS_MATRIX: AccessRow[] = [
  { method: "GET", path: "/api/ai-work", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "POST", path: "/api/ai-work", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "POST", path: "/api/auth/login", cls: "deny-only",
    allow: [], deny: [] },
  { method: "GET", path: "/api/bank/accounts", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "POST", path: "/api/bank/accounts", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "DELETE", path: "/api/bank/accounts/:id", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "PATCH", path: "/api/bank/accounts/:id", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/bank/balances", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/bank/cashflow", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/bank/hidden-payees", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "POST", path: "/api/bank/hidden-payees", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "DELETE", path: "/api/bank/hidden-payees/:id", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/bank/incoming", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/bank/outgoing", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/bank/receivables", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/bank/requisites", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/conversion", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/conversion-timeseries", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "GET", path: "/api/dashboard/daily", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "GET", path: "/api/dashboard/data-quality", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "POST", path: "/api/dashboard/deal-note", cls: "deny-only",
    allow: [], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/expected-deals", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "GET", path: "/api/dashboard/funnel", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/funnel-plan", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "POST", path: "/api/dashboard/funnel-plan", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/dashboard/funnel-report", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/funnel-weekly", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "GET", path: "/api/dashboard/kvp-extra", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/dashboard/kvp-plan", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "POST", path: "/api/dashboard/kvp-plan", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/dashboard/kvp-report", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/dashboard/kvp-report/manager-detail", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/lead-quality", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/dashboard/lead-recommendation", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["manager", "hr"] },
  { method: "GET", path: "/api/dashboard/leadgen", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/leadgen-regulars", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  // ФАЗА A · «Постійні клієнти · план місяця». Межа — вкладка `loyalty`, якої в
  // HR немає (перевірено в БД: ключа `loyalty` у screen_access ролі hr немає
  // взагалі). Менеджер вкладку МАЄ і бачить своїх клієнтів — звуження робить
  // скоуп усередині роута, а не відмова на вході.
  { method: "GET", path: "/api/dashboard/client-plans", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/client-comments?clientKey=zzz", cls: "GET",
    allow: [], deny: ["hr"] },
  { method: "POST", path: "/api/dashboard/client-comments", cls: "deny-only",
    allow: [], deny: ["hr"] },
  { method: "POST", path: "/api/dashboard/client-plan", cls: "deny-only",
    allow: [], deny: ["hr"] },
  { method: "POST", path: "/api/dashboard/client-plan/return", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "POST", path: "/api/dashboard/client-plans/submit", cls: "deny-only",
    allow: [], deny: ["hr"] },
  { method: "POST", path: "/api/dashboard/client-plans/approve-all", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  // ФАЗА B · реактивація. Читання — уся вкладка `loyalty` (HR її не має);
  // злиття й призначення відповідального — за ПРАВОМ `merge_clients`
  // (КВП, ОД, admin — зміна політики 03.08.2026), тому там deny значно ширший.
  { method: "GET", path: "/api/dashboard/reactivation-list", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "POST", path: "/api/dashboard/client-seasonal", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/dashboard/client-merge/preview?alias=a&canonical=b", cls: "GET",
    allow: ["admin", "kvp", "opdir"], deny: ["hr", "manager", "team_lead", "financier", "ceo"] },
  { method: "GET", path: "/api/dashboard/client-merge/journal", cls: "GET",
    allow: ["admin", "kvp", "opdir"], deny: ["hr", "manager", "team_lead", "financier", "ceo"] },
  { method: "POST", path: "/api/dashboard/client-merge", cls: "deny-only",
    allow: [], deny: ["hr", "manager", "team_lead", "financier", "ceo"] },
  { method: "POST", path: "/api/dashboard/client-merge/revoke", cls: "deny-only",
    allow: [], deny: ["hr", "manager", "team_lead", "financier", "ceo"] },
  { method: "POST", path: "/api/dashboard/client-manager", cls: "deny-only",
    allow: [], deny: ["hr", "manager", "team_lead", "financier", "ceo"] },
  { method: "GET", path: "/api/dashboard/client-manager/history?clientKey=zzz", cls: "GET",
    allow: [], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/loyalty", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "POST", path: "/api/dashboard/loyalty-override", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "DELETE", path: "/api/dashboard/loyalty-override/:clientKey", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/dashboard/loyalty-overrides", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/dashboard/manager-report", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/dashboard/managers", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/dashboard/overview", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/personal", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/plans-grid", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/dashboard/reactivation", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "POST", path: "/api/dashboard/reactivation", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "PUT", path: "/api/dashboard/reactivation", cls: "deny-only",
    allow: [], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/reactivation-candidates", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "DELETE", path: "/api/dashboard/reactivation/:clientKey", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/dashboard/receivables", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "PUT", path: "/api/dashboard/receivables/invoice-note", cls: "deny-only",
    allow: [], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/receivables/invoices", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "PUT", path: "/api/dashboard/receivables/note", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/dashboard/regular-clients", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/dashboard/repeat-client-history", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "POST", path: "/api/dashboard/repeat-client-plan", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "POST", path: "/api/dashboard/repeat-client-plan/approve", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "POST", path: "/api/dashboard/repeat-client-plan/approve-all", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/dashboard/repeat-client-plan/history", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/dashboard/repeat-plans-grid", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/dashboard/report", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/report-plan", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/report-plan/deals", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/response-time", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/dashboard/stuck-deals", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/dashboard/stuck-deals-grouped", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "POST", path: "/api/dashboard/sync", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "POST", path: "/api/dashboard/sync-receivables", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/dashboard/sync-status", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "GET", path: "/api/dashboard/teams", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/dashboard/timeseries", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "POST", path: "/api/documents/file", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "DELETE", path: "/api/documents/file/:id", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "PATCH", path: "/api/documents/file/:id", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/documents/file/:id/download", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "POST", path: "/api/documents/folder", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "DELETE", path: "/api/documents/folder/:id", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "PATCH", path: "/api/documents/folder/:id", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/documents/tree", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "GET", path: "/api/duty", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "POST", path: "/api/duty", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "DELETE", path: "/api/duty/:id", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "POST", path: "/api/duty/absences", cls: "deny-only",
    allow: [], deny: [] },
  { method: "DELETE", path: "/api/duty/absences/:id", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "POST", path: "/api/duty/absences/:id/approve", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "POST", path: "/api/duty/absences/:id/reject", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "POST", path: "/api/duty/holidays", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "DELETE", path: "/api/duty/holidays/:id", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/duty/presence", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "GET", path: "/api/feedback", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "POST", path: "/api/feedback", cls: "deny-only",
    allow: [], deny: [] },
  { method: "PATCH", path: "/api/feedback/:id", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/goals", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "POST", path: "/api/goals", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "DELETE", path: "/api/goals/:id", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "PATCH", path: "/api/goals/:id", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/messages/:userId", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "POST", path: "/api/messages/:userId", cls: "deny-only",
    allow: [], deny: [] },
  { method: "POST", path: "/api/messages/heartbeat", cls: "deny-only",
    allow: [], deny: [] },
  { method: "GET", path: "/api/messages/unread", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "GET", path: "/api/messages/users", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "GET", path: "/api/news", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "POST", path: "/api/news", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "DELETE", path: "/api/news/:id", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/news/km-prices", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "PUT", path: "/api/news/km-prices", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/one-on-ones/conduct-types", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead"], deny: ["manager"] },
  { method: "GET", path: "/api/one-on-ones/enps", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead"], deny: ["manager"] },
  { method: "GET", path: "/api/one-on-ones/forms/:type", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead"], deny: ["manager"] },
  { method: "PUT", path: "/api/one-on-ones/forms/:type", cls: "deny-only",
    allow: [], deny: ["admin", "kvp", "financier", "team_lead", "manager"] },
  { method: "GET", path: "/api/one-on-ones/forms/:type/versions", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead"], deny: ["manager"] },
  { method: "GET", path: "/api/one-on-ones/meetings/:type/:managerId", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead"], deny: ["manager"] },
  { method: "GET", path: "/api/one-on-ones/open-tasks/:type/:managerId", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead"], deny: ["manager"] },
  { method: "POST", path: "/api/one-on-ones/record", cls: "deny-only",
    allow: [], deny: ["manager"] },
  { method: "GET", path: "/api/one-on-ones/record/:type/:managerId", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead"], deny: ["manager"] },
  { method: "GET", path: "/api/one-on-ones/stats/scores", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead"], deny: ["manager"] },
  { method: "GET", path: "/api/one-on-ones/subjects", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead"], deny: ["manager"] },
  { method: "POST", path: "/api/one-on-ones/task", cls: "deny-only",
    allow: [], deny: ["manager"] },
  { method: "POST", path: "/api/one-on-ones/task/:id/review", cls: "deny-only",
    allow: [], deny: ["manager"] },
  { method: "GET", path: "/api/plans", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "POST", path: "/api/plans", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/plans/formation", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "POST", path: "/api/plans/formation/approve", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/plans/formation/repeat-clients", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "POST", path: "/api/plans/formation/return", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "POST", path: "/api/plans/formation/submit", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "POST", path: "/api/rates/analyze", cls: "deny-only",
    allow: [], deny: ["hr"] },
  { method: "GET", path: "/api/rates/bodytypes", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/rates/carriers", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/rates/city-info", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "POST", path: "/api/rates/city-info", cls: "deny-only",
    allow: [], deny: ["hr"] },
  { method: "DELETE", path: "/api/rates/city-info/:id", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/rates/health", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/rates/stats", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/rates/towns", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/reports", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "DELETE", path: "/api/reports/:id", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/settings", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "PUT", path: "/api/settings", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/settings/audit", cls: "GET",
    allow: ["admin", "ceo", "opdir"], deny: ["kvp", "financier", "hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/settings/roles", cls: "GET",
    allow: ["admin", "ceo", "opdir"], deny: ["kvp", "financier", "hr", "team_lead", "manager"] },
  { method: "POST", path: "/api/settings/roles", cls: "deny-only",
    allow: [], deny: ["kvp", "financier", "hr", "team_lead", "manager"] },
  { method: "DELETE", path: "/api/settings/roles/:key", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir"], deny: ["kvp", "financier", "hr", "team_lead", "manager"] },
  { method: "PUT", path: "/api/settings/roles/:key", cls: "deny-only",
    allow: [], deny: ["kvp", "financier", "hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/settings/users", cls: "GET",
    allow: ["admin", "ceo", "opdir"], deny: ["kvp", "financier", "hr", "team_lead", "manager"] },
  { method: "POST", path: "/api/settings/users", cls: "deny-only",
    allow: [], deny: ["kvp", "financier", "hr", "team_lead", "manager"] },
  { method: "PATCH", path: "/api/settings/users/:id", cls: "deny-only",
    allow: [], deny: ["kvp", "financier", "hr", "team_lead", "manager"] },
  { method: "POST", path: "/api/settings/users/:id/reactivate", cls: "deny-only",
    allow: [], deny: ["kvp", "financier", "hr", "team_lead", "manager"] },
  { method: "POST", path: "/api/settings/users/:id/reset-password", cls: "deny-only",
    allow: [], deny: ["kvp", "financier", "hr", "team_lead", "manager"] },
  { method: "POST", path: "/api/settings/users/provision", cls: "deny-only",
    allow: [], deny: ["kvp", "financier", "hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/statistics", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "GET", path: "/api/statistics/catalog", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "PUT", path: "/api/statistics/manual", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/statistics/series", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead", "manager"], deny: ["hr"] },
  { method: "POST", path: "/api/statistics/series/manual", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/tasks", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "POST", path: "/api/tasks", cls: "deny-only",
    allow: [], deny: [] },
  { method: "DELETE", path: "/api/tasks/:id", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "PATCH", path: "/api/tasks/:id", cls: "deny-only",
    allow: [], deny: [] },
  { method: "POST", path: "/api/tasks/plan", cls: "deny-only",
    allow: [], deny: [] },
  { method: "POST", path: "/api/tasks/reactivation", cls: "deny-only",
    allow: [], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/teams", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "GET", path: "/api/teams/managers", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "team_lead"], deny: ["hr", "manager"] },
  { method: "POST", path: "/api/tracker/auth", cls: "deny-only",
    allow: [], deny: [] },
  { method: "POST", path: "/api/tracker/heartbeat", cls: "deny-only",
    allow: [], deny: [] },
  { method: "POST", path: "/api/tracker/logout", cls: "deny-only",
    allow: [], deny: [] },
  { method: "POST", path: "/api/training/folder", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "DELETE", path: "/api/training/folder/:id", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "PATCH", path: "/api/training/folder/:id", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "POST", path: "/api/training/material", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "DELETE", path: "/api/training/material/:id", cls: "DELETE-ghost",
    allow: ["admin", "ceo", "opdir", "kvp", "financier"], deny: ["hr", "team_lead", "manager"] },
  { method: "PATCH", path: "/api/training/material/:id", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/training/material/:id/file", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "POST", path: "/api/training/materials/:id/publish", cls: "deny-only",
    allow: [], deny: ["hr", "team_lead", "manager"] },
  { method: "GET", path: "/api/training/tree", cls: "GET",
    allow: ["admin", "ceo", "opdir", "kvp", "financier", "hr", "team_lead", "manager"], deny: [] },
  { method: "POST", path: "/api/uploads", cls: "deny-only",
    allow: [], deny: [] },
];
